# Generated by Django 4.0.1 on 2022-02-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clonesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
